Add Clout Price of Creator Coin in Profiles
bitclout/frontend pull request #119
Opened 2021-06-10 07:47 UTC by carsenk

Adds in the current $CLOUT price of a Creator's Coin on Profile Pages, also includes a new BitClout logo in svg format for use with theming or any other future needed icons.

Preview:
![image](https://user-images.githubusercontent.com/10162347/121485644-9c9c6900-c98d-11eb-8939-59b3fdd9c8ea.png)

2021-06-12 18:52 UTC, carsenk commented
@lazynina @maebeam @diamondhands0 needs review/merge 👍

2021-06-14 21:35 UTC, carsenk commented
@lazynina ?

2021-06-15 00:20 UTC, lazynina requested changes
Other than removing the `~` I like this change. will wait on @maebeam for a second opinion.

2021-06-15 00:20 UTC, lazynina commented on src/app/creator-profile-page/creator-profile-top-card/creator-profile-top-card.component.html
> +          ~{{ globalVars.nanosToUSD(profile.CoinPriceBitCloutNanos, 2) }} (<strong>~<img src="assets/img/cloutlogo.svg" width="15px" class="clout" style="margin-right:-8px;margin-top:-2px;" />
I would remove the `~` from within the parentheses.  It feels redundant to me.

2021-06-15 02:39 UTC, carsenk commented
Fixed and awaiting @maebeam

2021-06-15 16:42 UTC, maebeam commented on src/app/creator-profile-page/creator-profile-top-card/creator-profile-top-card.component.html
> +        <div class="fc-muted" style="display: inline">Price&nbsp;&nbsp;</div>
Let's keep the Coin Price copy for now

2021-06-15 16:54 UTC, carsenk commented on src/app/creator-profile-page/creator-profile-top-card/creator-profile-top-card.component.html
> +        <div class="fc-muted" style="display: inline">Price&nbsp;&nbsp;</div>
Okay

2021-06-15 17:01 UTC, merged