Updates to Wallet Page
bitclout/frontend pull request #120
Opened 2021-06-10 08:36 UTC by carsenk

This adds in a Total Balance at the top of the Wallet page along with the total count of creator coins held and clout balance information. Also added missing "CLOUT" tags, if we want to use a different ticker feel free to lmk @maebeam 

Preview:
![walletupdatesfkdljfskldf](https://user-images.githubusercontent.com/10162347/121492926-8e058000-c994-11eb-83e3-b6b30c926f8c.png)

2021-06-14 23:41 UTC, carsenk commented
@maebeam @lazynina thoughts on this PR also? Should be good to go if wanted

2021-06-15 00:18 UTC, lazynina requested changes
I like these additions to the wallet, but would like to use $CLOUT instead of just CLOUT.  We're trying to move to getting two reviews before merging, so will wait on @maebeam for a second review.

2021-06-15 02:22 UTC, lazynina approved these changes

2021-06-15 16:44 UTC, maebeam approved these changes

2021-06-15 16:44 UTC, merged