cake-theme.ts
bitclout/frontend pull request #230
Opened 2021-07-06 06:24 UTC by teambrixmusic

Hey there! Don't expect this to actually merge and not certain I remember what I'm doing but Tijn inspired me to do a PR and I loved Carsenk themes so (I'm not completely sure what this looks like yet) but this is an alternative lightTheme in festive childlike pastels colors. The luminosity of the original theme colors are relatively the same so the contrast shouldn't change. Simply, the whites and greys have become slightly tinted pinks and blues and the darker colors have taken on shades of purple and blue. It's a bit whacky, and intended on looking like a silly myspace-ish birthday cake throwback— perhaps for fun, to use on your Birthday. Or a teen might like it.

In all seriousness, when my node is back up and I figure out Git on Windows, I'll have more to add. 

Won't take a rejection personally, was just for fun and to learn again. <3

2021-07-06 06:43 UTC, lazynina commented
![image](https://user-images.githubusercontent.com/81658138/124554085-6914f900-ddea-11eb-820c-2c11fd6035aa.png)
had to make a few modifications to get it working, but here's what it looks like if you want to see! 

You'll need to modify `app.module` with the following lines:
around line 128
```
import { cakeTheme } from "./theme/cake-theme";
```

and modify around line 250
```
      themes: [lightTheme, darkTheme, icydarkTheme, legendsTheme, cakeTheme],
```

2021-07-06 06:46 UTC, lazynina requested changes
see my feedback above

2021-07-06 10:51 UTC, teambrixmusic commented
> see my feedback above

Ah! I wasn't sure which classes went to which. Thanks! On it. Will give it a shot. :) BRB

2021-07-06 13:46 UTC, teambrixmusic commented
I think I did it right this time lol. Let me know.

![cake](https://user-images.githubusercontent.com/82254764/124610967-fda94680-de3e-11eb-9253-72b6771f5ecf.jpg)

2021-07-06 14:07 UTC, teambrixmusic commented
Your screenshots look so much better than mine @lazynina 
Is the logo filter too pink? It matches the hearts (hot pink)
@carsenk Wish we could break out more theme classes i.e. .feed-post__blue-border & .tab-underline-active are very visible selection markers. Even if it could match link color by default.
Just realized how fun this would look with the confetti animation lol!

2021-07-07 01:48 UTC, lazynina approved these changes

2021-07-07 01:48 UTC, lazynina commented on src/app/theme/cake-theme.ts
> +    "--filter": "blur(0.6px) grayscale(0.5) sepia(1) hue-rotate(227deg) saturate(9.2) opacity(0.78)",
```suggestion
    "--filter": "grayscale(0.5) sepia(1) hue-rotate(227deg) saturate(9.2) opacity(0.78)",
```
the blur seems unnecessary and just makes the logo look strange.

2021-07-07 01:48 UTC, merged