Added hover animations to post icons
bitclout/frontend pull request #231
Opened 2021-07-06 07:19 UTC by AdityaChaudhary0005

Preview of hover animations on post icons: 

![Hover PR](https://user-images.githubusercontent.com/55331140/124558664-79fc5380-de58-11eb-8d2c-3bf45c84fe7a.gif)

2021-07-06 14:14 UTC, teambrixmusic commented
So cool!

2021-07-06 14:34 UTC, tijno commented
@AdityaChaudhary0005 nice! you might want to check with sourdough on bitclout or cloutedones discord - i know she had suggestion for making the icon animation better for accessibility on mobile devices. May be an opportunity to consider that.

2021-07-06 14:47 UTC, AdityaChaudhary0005 commented
Thanks @teambrixmusic and @tijno !

yeah, i will consider contacting sourdough!

2021-07-07 01:07 UTC, lazynina requested changes
this looks good to me!  @tijno, we can consider improvements to the icon animation for mobile in a separate PR.

2021-07-07 01:07 UTC, lazynina commented on src/styles.scss
> +
```suggestion
```

2021-07-07 01:07 UTC, lazynina approved these changes

2021-07-07 01:08 UTC, merged