New greenish theme
bitclout/frontend pull request #248
Opened 2021-07-07 21:14 UTC by harpreet9629

Here's New Theme for BitClout

![Screenshot_5](https://user-images.githubusercontent.com/26606638/124829514-5c350880-df96-11eb-83a7-9a4e0ca3dc2c.jpg)

2021-07-07 23:15 UTC, lazynina requested changes
There are three different theme files added. Which one is the one you're adding? Also, it needs to be imported in app-module; otherwise, it can't be selected in the settings page.

Also, please remove the addition of button properties as that is a separate feature.

2021-07-08 03:19 UTC, harpreet9629 commented
Ok i do, thank you

2021-07-08 06:07 UTC, harpreet9629 commented
@lazynina Its Fixed 👍

2021-07-08 20:19 UTC, lazynina requested changes

2021-07-08 20:19 UTC, lazynina commented on src/app/theme/greenish-theme.ts
> +    "--loading": "#ffffff",
add button property
```suggestion"
    "--button": "#03A8BB",
    "--loading": "#ffffff", 
```

2021-07-08 20:19 UTC, lazynina commented on src/app/theme/greenish-theme.ts
> +//"--button": "#03A8BB",
```suggestion
```

2021-07-08 20:25 UTC, harpreet9629 commented on src/app/theme/gray-theme.ts
> +import { Theme } from "./symbols";
It's Deleted

2021-07-08 20:28 UTC, harpreet9629 commented on src/app/theme/greenish-theme.ts
> +import { Theme } from "./symbols";
Its Done i changed theme name in greenish-theme.ts file
![image](https://user-images.githubusercontent.com/26606638/124986263-0d9c7280-e059-11eb-9e5a-f58b22f42ede.png)

2021-07-08 20:42 UTC, harpreet9629 commented on src/app/theme/icy-dark-theme.ts
> +    "--button": "#3a9eea",
It show me my branch already merge with main

2021-07-08 21:26 UTC, merged

2021-07-08 21:26 UTC, lazynina approved these changes

2021-07-08 21:34 UTC, harpreet9629 commented
Thank You Guys :)

I will come back with more changes

2021-07-09 07:00 UTC, LvlUpGuy commented
This almost has a "Emerald" feeling to it.

I like it and will most assuredly try it.