Update sign-up.component.html
bitclout/frontend pull request #253
Opened 2021-07-08 21:48 UTC by CoderDrShen

2021-07-08 23:44 UTC, lazynina requested changes

2021-07-08 23:44 UTC, lazynina commented on src/app/sign-up/sign-up.component.html
> +        Buy $Clout
```suggestion
        Buy $CLOUT
```

2021-07-08 23:44 UTC, lazynina commented on src/app/sign-up/sign-up.component.html
> +          $Clout is a
```suggestion
          $CLOUT is a
```

2021-07-08 23:44 UTC, lazynina commented on src/app/sign-up/sign-up.component.html
> +        You can use $Clout to trade creator coins, give Diamonds, buy NFTs (coming soon), and much more.
```suggestion
        You can use $CLOUT to trade creator coins, give Diamonds, buy NFTs (coming soon), and much more.
```

2021-07-09 16:15 UTC, maebeam approved these changes

2021-07-09 21:32 UTC, lazynina approved these changes

2021-07-09 21:32 UTC, merged