Update buy-bitclout-usd.component.html
bitclout/frontend pull request #254
Opened 2021-07-08 22:02 UTC by ShhubhamA

2nd PR just increasing my merge lol

2021-07-08 22:28 UTC, CoderDrShen commented
I am working on Turkish Node. That's why I wanted to fix minor mistakes.

2021-07-08 23:45 UTC, lazynina requested changes

2021-07-08 23:45 UTC, lazynina commented on src/app/buy-bitclout-page/buy-bitclout-usd/buy-bitclout-usd.component.html
> +    <div class="fs-18px font-weight-bold mb-10px">Enter an amount in USD to convert to $Clout</div>
```suggestion
    <div class="fs-18px font-weight-bold mb-10px">Enter an amount in USD to convert to $CLOUT</div>
```

2021-07-08 23:45 UTC, lazynina commented on src/app/buy-bitclout-page/buy-bitclout-usd/buy-bitclout-usd.component.html
> +    <p class="mb-5px">You can purchase up to ${{ maxUsdAmount }} of $Clout per week using USD.</p>
```suggestion
    <p class="mb-5px">You can purchase up to ${{ maxUsdAmount }} of $CLOUT per week using USD.</p>
```

2021-07-08 23:45 UTC, lazynina commented on src/app/buy-bitclout-page/buy-bitclout-usd/buy-bitclout-usd.component.html
> +      Buy $Clout
```suggestion
      Buy $CLOUT
```

2021-07-09 05:28 UTC, lazynina approved these changes

2021-07-09 21:32 UTC, merged