Add verified checkmark in notifications
bitclout/frontend pull request #262
Opened 2021-07-10 14:41 UTC by harpreet9629

There is 1 small thing that is missing, User Verified Checkmark in Notifications.

I added that, Thanks to @AdityaChaudhary0005 for the suggestion :)

![Screenshot 2021-07-10 at 20-03-08 Welcome to BitClout](https://user-images.githubusercontent.com/26606638/125166807-f1b0e200-e1ba-11eb-941a-5fea9062b4f1.png)

2021-07-10 14:45 UTC, ShhubhamA commented
The  amount of PR you are doing the core devs should pay you lol :)

2021-07-10 14:51 UTC, maebeam commented
If you could fix the horizontal alignment I think I like this change. Will ask for input from @lazynina before approving

2021-07-10 14:58 UTC, harpreet9629 commented
I did vertical alignment top, should I make it to the center?

2021-07-10 14:59 UTC, AdityaChaudhary0005 commented
Yes, center would be apt

2021-07-10 15:24 UTC, harpreet9629 commented
Fixed
![Screenshot_1](https://user-images.githubusercontent.com/26606638/125168002-f4163a80-e1c0-11eb-9ac6-d545017086cb.jpg)

2021-07-10 16:01 UTC, harpreet9629 commented
> 
> 
> Awesome ! The amount of PR and merge you are doing the core devs should at least verify you and maybe pay you too lol :) 😛

Thank you, for support

2021-07-10 19:02 UTC, lazynina requested changes
I like this change - some small code clean up requested before approving this one.

2021-07-10 19:02 UTC, lazynina commented on src/app/notifications-page/notifications-list/notifications-list.component.ts
> +    //const actorName = `<b>${actor.Username}</b>`;
```suggestion
```

2021-07-10 19:02 UTC, lazynina commented on src/app/notifications-page/notifications-list/notifications-list.component.ts
> +    const actorName = (actor.IsVerified) ? `<b>${actor.Username}</b><span class="ml-1 d-inline-block align-center text-primary fs-12px">
```suggestion
    const actorName = actor.IsVerified ? `<b>${actor.Username}</b><span class="ml-1 d-inline-block align-center text-primary fs-12px">
```

2021-07-11 02:30 UTC, harpreet9629 commented
All Done

2021-07-12 19:47 UTC, lazynina approved these changes

2021-07-12 19:47 UTC, merged