fix: removed page refresh when nft bid is made
bitclout/frontend pull request #366
Opened 2021-08-04 22:20 UTC by superzordon

2021-08-05 00:07 UTC, maebeam commented
We need to pull fresh data so you can see your bid you've placed

2021-08-10 18:13 UTC, lazynina commented
@superzordon we need to handle the case where a user submits a bid from the nft-post-page. It looks like we only update the feed-post's NFT entries when that happens. I'd suggest that we emit an event from feed-post in the subscription to the onHide event for the `PlaceBidModalComponent`. The NFT Post Page component should bind to that event and then perform the following code:
```
this.loading = true;
this.refreshPosts();
```

2021-08-10 21:00 UTC, lazynina requested changes
after line 585, add `this.nftBidPlaced.emit()` to trigger the nft post page to refresh its bids.

2021-08-10 21:00 UTC, lazynina commented on src/app/nft-post-page/nft-post/nft-post.component.ts
> +    this.refreshPosts();
we only need to call `this.refreshBidData()` actually - sorry!

2021-08-11 21:11 UTC, lazynina commented on src/app/nft-post-page/nft-post/nft-post.component.ts
> +import {ChangeDetectorRef, Component, ViewChild} from "@angular/core";
```suggestion
import { ChangeDetectorRef, Component, ViewChild } from "@angular/core";
```

2021-08-11 21:20 UTC, lazynina approved these changes
nice work!

2021-08-11 21:33 UTC, merged